confirmModulesPurge: false
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
nodeLinker: hoisted # see https://pnpm.io/settings#nodelinker
overrides:
  "@types/codemirror": "5.60.17"
packages:
  - .
minimumReleaseAgeExclude:
  - "@divi/conversion@1.0.4"
  - "@divi/field-library@1.0.10 || 1.0.11"
  - "@divi/modal@1.0.5"
  - "@divi/module-library@1.0.11 || 1.0.12"
  - "@divi/module-utils@1.0.11 || 1.0.12"
  - "@divi/module@1.0.11 || 1.0.12"
  - "@divi/script-library@1.0.10"
  - "@divi/style-library@1.0.8"
  - "@divi/types@1.0.10 || 1.0.11"
  - "@wordpress/hooks@4.52.0 || 4.53.0"
  - "@wordpress/i18n@6.25.0 || 6.26.0"
  - postcss@8.5.25
  - "@divi/context-library@1.0.3"
  - globals@17.11.0
  - "@volksverpetzer/design-tokens@0.1.0 || 0.3.0"
  - "@volksverpetzer/ui-web@0.2.0 || 0.3.0"
