confirmModulesPurge: false
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
nodeLinker: hoisted # see https://pnpm.io/settings#nodelinker
overrides:
  "@types/codemirror": "5.60.17"
packages:
  - .
minimumReleaseAgeExclude:
  - globals@17.8.0
